'use client'

import { useEffect } from "react";
import { useState } from "react";
import { Button } from "@mui/material";
import { useRouter } from 'next/navigation';
import styles from "./page_styles.module.css";
import globalstate from "@/globalstate";

const cardColors = [ "#3357FF", "#FF5733", "#33FF57", "#FF33A1", "gold"];
const ct = ["Water Gun", "Card 2", "Card 3", "Card 4", "Original Story"];
const cd = [
    "A man took a seat at the bar and asked the barkeeper for a glass of water. After giving Philip his water, the barkeeper pulled out a gun and pointed it at the his head. The man never drank his glass of water. He thanked the barkeeper and left.",
    "Description for Card 2",
    "Description for Card 3",
    "Description for Card 4",
    "A Completely new story generated by LLM, more specifically GPT-4o. This story is unique and has never been told before.",
];

export default function RootPg() {
    const [selectedCard, setSelectedCard] = useState<number | null>(null);
    const [apiKey, setApiKey] = useState<string>('');
    const [cardTitles, setCardTitles] = useState(ct);
    const [cardDescriptions, setCardDescriptions] = useState(cd);
    const router = useRouter();

    // Fetch card data from JSON file
    useEffect(() => {
        const fetchCardData = async () => {
            const response = await fetch('/stories.json');
            const data = await response.json();
            setCardTitles(data.map((card: any) => card.title));
            setCardDescriptions(data.map((card: any) => card.description));
            console.log('Fetching card data...');
        };
    
        fetchCardData();
    
    }, []);

    const handleApiKeyChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        setApiKey(e.target.value);
    }

    const navigateToHome = () => {
        globalstate.apiKey = apiKey;
        router.push('/game');
    }

    const handleCardClick = (index: number) => {
        setSelectedCard(index);
    }

    const closeCard = () => {
        setSelectedCard(null);
    }

    return (
        <div className={styles.wrappedPage}>
            <div className={styles.main}>
                <h1 className={styles.title}>Historias CInistras</h1>
                <div className={styles.cardsContainer}>
                    {cardColors.slice(0, 4).map((color, index) => (
                        <div
                            key={index}
                            className={styles.card}
                            style={{ backgroundColor: color }}
                            onClick={() => handleCardClick(index)}
                        >
                            <h2 className={styles.cardTitle}>{cardTitles[index]}</h2>
                        </div>
                    ))}
                    <div
                        className={`${styles.card} ${styles.specialCard}`}
                        style={{ backgroundColor: cardColors[4] }}
                        onClick={() => handleCardClick(4)}
                    >
                        <h2 className={styles.cardTitle}>{cardTitles[4]}</h2>
                    </div>
                </div>

                {selectedCard !== null && (
                    <div className={styles.modalOverlay}>
                        <div className={styles.modal}>
                            <h2>{cardTitles[selectedCard]}</h2>
                            <p>{cardDescriptions[selectedCard]}</p>
                            <input
                                id={`apiKey-${selectedCard}`}
                                type="password"
                                value={apiKey}
                                onChange={handleApiKeyChange}
                                placeholder="Enter your API Key"
                                className={styles.apiKeyInput}
                            />
                            <Button className={styles.submitButton} onClick={navigateToHome}>
                                Start
                            </Button>
                            <Button className={styles.closeButton} onClick={closeCard}>
                                Close
                            </Button>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
}
